Updated HowToBuild.txt document for VisualStudio 2013: Removed deprecated x360ce.sln and renamed  x360ce_All.sln to x360ce.sln
Note: dinput8  and libMiniHook projects builds successfully, but x360ce build results in error:
Error 2 error C4996: 'GetVersionExA': was declared deprecated 
c:\proj\racer_s\x360ce\x360ce\x360ce\utilities\misc.h 173 1 x360ce